name: ahorramax
description: App AhorraMax - Ahorro y recomendaciones AI
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2

  # ✅ Firebase (versiones compatibles y estables)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  cloud_functions: ^5.2.4

  # Autenticación con Google (revisada)
  google_sign_in: ^6.2.1

  # Utilidades
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.1
  flutter_dotenv: 6.0.0
  http: ^1.2.2
  google_generative_ai: ^0.4.3
  audioplayers: ^6.0.0

  image_picker: ^1.1.2
  geolocator: ^13.0.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2
  qr_flutter: ^4.1.0
  share_plus: ^10.0.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  image_cropper: ^10.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true

  # Deshabilitar sonidos para evitar errores
  # assets:
  #   - assets/audio/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
